# Setup
title: 결국은 개발자
description: 한걸음씩 성실하고 부지런하게 차곡차곡 쌓는 중 입니다.
url: https://seuunng.github.io
avatar: /assets/images/avatar.jpeg 
permalink: pretty
cover_image: /assets/images/bg.jpeg
# Include specific folders
# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/blog/:num/"

collections:
  logs:
    output: true
    
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: seung-hee, park
  links:
    - https://github.com/seuunng
    - https://blog.naver.com/alldaytt
    - www.youtube.com/@juumjump

google_site_verification: xxxxx
lang: ko

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: 개발자씅
  url: https://github.com/seuunng/
  email: mnb2856@gmail.com
