- project_name: A Diary for the Lazybones
  description: A simple and beautiful, powerful diary for lazybones like me.
  url: /project/diaryProject/index
  cover_image: /project.jpeg
  period: 2024
- 