- project_name: A Diary for the Lazybones
  description: A simple and beautiful, powerful diary for lazybones like me.
  url: /project/diaryProject/
  cover_image: assets/images/project.jpg
  period: 2024
- 